openapi: 3.0.1
info:
  title: securitydomain
  description: 'Servicio encargado de los procesos de autenticación'
  version: '2.0'
servers:
  - url: http://apis.pfcti.com/services/securitydomain/api/v2.0
paths:
  /users/signin:
    post:
      summary: Login
      description: Verifica la identidad y credenciales del usuario en el sistema de autenticación.
      operationId: signin
      tags:
        - Authentication
        - Installments
      parameters:
        - name: Accept-Language
          in: header
          description: Idioma
          required: true
          schema:
            enum:
              - es
              - en
              - es-CR
              - es-NI
              - es-GT
              - es-HN
              - es-PA
              - es-DO
              - es-SV
              - es-KY
              - es-EC
              - en-CR
              - en-NI
              - en-GT
              - en-HN
              - en-PA
              - en-DO
              - en-SV
              - en-KY
              - en-EC
            type: string
        - name: X-Origin-IP-Address
          in: header
          description: IP que originó el request al servicio.
          required: true
          schema:
            type: string
            format: ipv4, ipv6
        - name: X-Subscription-Id
          in: header
          description: Identificador del sistema.
          required: true
          schema:
            type: string
        - name: X-Transaction-Id
          in: header
          description: Identificador único de la transacción.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 38
        - name: X-User-Code
          in: header
          description: Código de usuario que utiliza el cliente que realiza el request. O bien, valores que permitan identificar usuario (persona o sistema) de una solicitud.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 50
        - name: X-Origin-Country
          in: header
          description: Código de país a 2 caracteres según estándar ISO 3166-1 alfa-2.
          required: true
          schema:
            type: string
            minLength: 2
            maxLength: 2
            enum:
              - CR
              - NI
              - GT
              - HN
              - PA
              - DO
              - SV
              - KY
              - EC
        - name: X-Origin-MachineName
          in: header
          description: Nombre del servidor/maquina en donde se inicia el request.
          required: false
          schema:
            type: string
            minLength: 2
            maxLength: 255
        - name: X-Point-Coordinates
          in: header
          description: Localización en donde el usuario final realiza el evento. El formato esperado es GPS ISO 6709.
          required: false
          schema:
            type: string
            minLength: 20
            maxLength: 23
        - name: X-Kony-Api-Version
          in: header
          description: Versión de API que se está consumiendo. Requerido en servicios publicados en Quantum Fabric.
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 6
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignIn_Request_01'
            example:
              user: 
                code: jp7920
                password: Temp12309$
      responses:
        '200':
          description: Respuesta exitosa
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignIn_Response_200_01'
        '400':
          description: Respuesta fallida por error controlado.
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_400_01'
  /sessions/initialize:
    post:
      summary: Inicializar Sesión
      description: Inicializa la sessión, almacena datos y retorna el identificador correspondiente.
      operationId: initializesession
      tags:
        - Session
        - Installments
      parameters:
        - name: Accept-Language
          in: header
          description: Idioma
          required: true
          schema:
            enum:
              - es
              - en
              - es-CR
              - es-NI
              - es-GT
              - es-HN
              - es-PA
              - es-DO
              - es-SV
              - es-KY
              - es-EC
              - en-CR
              - en-NI
              - en-GT
              - en-HN
              - en-PA
              - en-DO
              - en-SV
              - en-KY
              - en-EC
            type: string
          example: es-NI
        - name: X-Origin-IP-Address
          in: header
          description: IP que originó el request al servicio.
          required: true
          schema:
            type: string
            format: ipv4, ipv6
          example: 192.168.1.57
        - name: X-Subscription-Id
          in: header
          description: Identificador del sistema.
          required: true
          schema:
            type: string
          example: NI10100010001FA25684685245836
        - name: X-Transaction-Id
          in: header
          description: Identificador único de la transacción.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 38
          example: 26f0e992-41ba-4e5b-b93f-6111bdea8177
        - name: X-User-Code
          in: header
          description: Código de usuario que utiliza el cliente que realiza el request. O bien, valores que permitan identificar usuario (persona o sistema) de una solicitud.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 50
          example: systemuser195
        - name: X-Origin-Country
          in: header
          description: Código de país a 2 caracteres según estándar ISO 3166-1 alfa-2.
          required: true
          schema:
            type: string
            minLength: 2
            maxLength: 2
            enum:
              - CR
              - NI
              - GT
              - HN
              - PA
              - DO
              - SV
              - KY
              - EC
          example: NI
        - name: X-Origin-MachineName
          in: header
          description: Nombre del servidor/maquina en donde se inicia el request.
          required: false
          schema:
            type: string
            minLength: 2
            maxLength: 255
          example: machine_name_01
        - name: X-Point-Coordinates
          in: header
          description: Localización en donde el usuario final realiza el evento. El formato esperado es GPS ISO 6709.
          required: false
          schema:
            type: string
            minLength: 20
            maxLength: 23
          example: 095953.88, -0840701.56
        - name: X-Kony-Api-Version
          in: header
          description: Versión de API que se está consumiendo. Requerido en servicios publicados en Quantum Fabric.
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 6
          example: 1.0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeSession_Request_01'
            example:
              session:
                sessionData:
                  customerId: 444444
                  lastFourDigits: 5865
      responses:
        '200':
          description: Respuesta exitosa
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitializeSession_Response_200_01'
        '400':
          description: Respuesta fallida por error controlado.
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_400_01'
  /sessions/validate:
    post:
      summary: Validar Sesión
      description: Valida si el identificador de la sesión es válido y está vigente, en cuyo caso retorna los datos almacenados en sesión.
      operationId: validatesession
      tags:
        - Session
        - Installments
      parameters:
        - name: Accept-Language
          in: header
          description: Idioma
          required: true
          schema:
            enum:
              - es
              - en
              - es-CR
              - es-NI
              - es-GT
              - es-HN
              - es-PA
              - es-DO
              - es-SV
              - es-KY
              - es-EC
              - en-CR
              - en-NI
              - en-GT
              - en-HN
              - en-PA
              - en-DO
              - en-SV
              - en-KY
              - en-EC
            type: string
          example: es-NI
        - name: X-Origin-IP-Address
          in: header
          description: IP que originó el request al servicio.
          required: true
          schema:
            type: string
            format: ipv4, ipv6
          example: 192.168.1.57
        - name: X-Subscription-Id
          in: header
          description: Identificador del sistema.
          required: true
          schema:
            type: string
          example: NI10100010001FA25684685245836
        - name: X-Transaction-Id
          in: header
          description: Identificador único de la transacción.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 38
          example: 26f0e992-41ba-4e5b-b93f-6111bdea8177
        - name: X-User-Code
          in: header
          description: Código de usuario que utiliza el cliente que realiza el request. O bien, valores que permitan identificar usuario (persona o sistema) de una solicitud.
          required: true
          schema:
            type: string
            minLength: 5
            maxLength: 50
          example: systemuser195
        - name: X-Origin-Country
          in: header
          description: Código de país a 2 caracteres según estándar ISO 3166-1 alfa-2.
          required: true
          schema:
            type: string
            minLength: 2
            maxLength: 2
            enum:
              - CR
              - NI
              - GT
              - HN
              - PA
              - DO
              - SV
              - KY
              - EC
          example: NI
        - name: X-Origin-MachineName
          in: header
          description: Nombre del servidor/maquina en donde se inicia el request.
          required: false
          schema:
            type: string
            minLength: 2
            maxLength: 255
          example: machine_name_01
        - name: X-Point-Coordinates
          in: header
          description: Localización en donde el usuario final realiza el evento. El formato esperado es GPS ISO 6709.
          required: false
          schema:
            type: string
            minLength: 20
            maxLength: 23
          example: 095953.88, -0840701.56
        - name: X-Kony-Api-Version
          in: header
          description: Versión de API que se está consumiendo. Requerido en servicios publicados en Quantum Fabric.
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 6
          example: 1.0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateSession_Request_01'
      responses:
        '200':
          description: Respuesta exitosa
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateSession_Response_200_01'
        '400':
          description: Respuesta fallida por error controlado.
          headers:
            X-Response-MachineName:
              description: Nombre del servidor en donde se procesa el request.
              schema:
                type: string
                minLength: 2
                maxLength: 255
                example: machine_name_01
            X-Response-IP-Address:
              description: Dirección IP en donde se procesó el request.
              schema:
                type: string
                minLength: 7
                maxLength: 45
                format: ipv4, ipv6
                example: 10.130.23.4, ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190
            X-Response-Url:
              description: Url en donde se procesó el request.
              schema:
                type: string
                minLength: 8
                maxLength: 2000
                format: url
                example: http://darkblik/api/v1/pkg/proc
            X-Response-Time:
              description: Duración de la ejecución en milisegundos.
              schema:
                type: string
                minLength: 3
                maxLength: 8
                example: 120ms
            X-Origin-Country:
              description: Código de país a 2 caracteres segun estandar ISO 3166-1 alfa-2.
              schema:
                type: string
                minLength: 2
                maxLength: 2
                enum:
                  - CR
                  - NI
                  - GT
                  - HN
                  - PA
                  - DO
                  - SV
                  - KY
                  - EC
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response_400_01'

components:
  schemas:
    # ---------------------------- #
    # ---- Request & Response ---- #
    # ---- Nomenclatura Request: Operacion_Request_Consecutivo (00) ---- #
    # ---- Nomenclatura Response: [Operacion_]Response_HttpCode_Consecutivo (00) ---- #
    InitializeSession_Request_01:
      required:
        - session
      type: object
      properties:
        session:
          description: Objeto que contiene los datos que se requiere almacenar en sesión. Cada sistema guarda los datos que necesite. Si solo necesita generar el token, sin almacenar datos en cache, no se envía este objeto.
          $ref: '#/components/schemas/Session_Data'
    InitializeSession_Response_200_01:
      required:
        - Data
      type: object
      properties:
        Data:
          required:
            - session
          type: object
          properties:
            session:
              $ref: '#/components/schemas/Session_Id'
          description: Objeto que contiene los datos de la respuesta.
      description: Se espera un código HTTP 200 OK como resultado de la operación.
    SignIn_Request_01:
      required:
        - user
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User_Code_Password'
    SignIn_Response_200_01:
      required:
        - Data
      type: object
      properties:
        Data:
          required:
            - user
          type: object
          properties:
            user:
              $ref: '#/components/schemas/User_AuthenticationInformation'
          description: Objeto que contiene los datos de la respuesta.
      description: Se espera un código HTTP 200 OK como resultado de la operación.
    Response_400_01:
      required:
        - Code
        - Id
        - Message
      type: object
      properties:
        Code:
          maxLength: 3
          minLength: 3
          type: string
          description: Corresponde al HTTP Status Code resultante de la ejecución del servicio.
          example: 460
        Message:
          maxLength: 200
          minLength: 1
          type: string
          description: Mensaje en lenguaje de alto nivel donde se expresa una descripción del error presentado.
          example: Error general en el proceso de la transacción.
        Id:
          maxLength: 50
          minLength: 1
          type: string
          description: 'Identificador único del evento de error presentado, normalmente relacionado a un registro en bitácora de errores para darle trazabilidad al soporte de la aplicación.'
          example: c4abb6dc-d0c4-4621-a63e-ee2df4e9f85f
        Errors:
          type: array
          items:
            required:
              - Path
              - Message
              - ErrorCode
              - Url
            type: object
            properties:
              Path:
                maxLength: 200
                minLength: 1
                type: string
                description: Hace referencia al path del campo en el JSON que contiene el error.
                example: Namespace.Class.Method
              Message:
                maxLength: 1000
                minLength: 1
                type: string
                description: 'Mensaje de índole técnica relacionada al error presentado, si se tiene un stacktrace debe agregarse como valor para esta llave.'
                example: Number may not have been initialized.
              ErrorCode:
                maxLength: 50
                minLength: 1
                type: string
                description: 'Código de error específico devuelto por el sistema, en caso de error no controlado que no muestre dicho código, se omite el llenado de este valor para dicha llave.'
                example: '50685489'
              Url:
                maxLength: 500
                minLength: 1
                type: string
                description: Hace referencia a documentación del error especifico o bien documentación del API.
                example: http://localhost/services/origin-service/resource
          description: Lista de errores registrados durante el procesamiento del request.
      description: Respuesta fallida por error controlado.
    ValidateSession_Request_01:
      required:
        - session
      type: object
      properties:
        session:
          description: Identificador de la sesión que se está validando.
          $ref: '#/components/schemas/Session_Id'
    ValidateSession_Response_200_01:
      required:
        - Data
      type: object
      properties:
        Data:
          required:
            - session
          type: object
          properties:
            session:
              $ref: '#/components/schemas/Session_Data'
          description: Objeto que contiene los datos de la respuesta.
      description: Se espera un código HTTP 200 OK como resultado de la operación.
      example:
        Data:
          session:
            customerId: '4444444'
            lastFourDigits: '6584'

    # ------------------ #
    # ---- Entities ---- #
    # ---- Nomenclatura: Entidad[_Parametro1_Parametro2_ParametroN] ---- #
    # ----               . Se usa la entidad sola cuando contiene todas sus propiedades ---- #
    AnyValue:
      description: Datos de cualquier tipo que se requieran enviar o recibir.
    AuthenticationInformation:
      required:
        - loginAttempts
        - passwordChangeDeadlineDays
        - passwordChangeDeadline
      type: object
      description: Información sobre el proceso de autenticación.
      properties:
        loginAttempts:
          type: integer
          description: Número restante de intentos de autenticación.
          example: 3
        passwordChangeDeadlineDays:
          type: integer
          description: Días para vencimiento de contraseña.
          example: 17
        passwordChangeDeadline:
          type: string
          description: Fecha de vencimiento de la contraseña.
          format: date-time
          example: '2021-03-17T16:02:28.000Z'
    Customer_Id:
      required:
        - id
      type: object
      description: Información del cliente.
      properties:
        id: 
          $ref: '#/components/schemas/Default_Customer_Id'
    Session_Data:
      description: Datos que están o van a ser almacenados en el caché de la sesión. La estructura de properties es flexible a las necesidades del sistema consumidor.
      $ref: "#/components/schemas/AnyValue"
      example:
        sessionData:
          customerId: '4444444'
          lastFourDigits: '6584'
    Session_Id:
      type: object
      description: Contiene información de la sesión.
      required:
        - id
      properties:
        id:
          $ref: '#components/schemas/Default_Session_Id'
    User_Code_Password:
      required:
        - code
        - password
      type: object
      description: Credenciales de autenticación del usuario.
      properties:
        code:
          $ref: '#/components/schemas/Default_User_Code'
        password:
          $ref: '#/components/schemas/Default_User_Password'
    User_AuthenticationInformation:
      type: object
      description: Información sobre el proceso de autenticación del usuario.
      required:
        - customer
        - authenticationInformation
      properties:
        customer:
          $ref: '#/components/schemas/Customer_Id'
        authenticationInformation:
          $ref: '#/components/schemas/AuthenticationInformation'

    # ------------------ #
    # ---- Definiciones Default ---- #
    # ---- Nomenclatura: Default_[Concepto] ---- #
    # ----               . Son definiciones estándar que pueden reutilizarse en muchas entidades ---- #
    Default_User_Code:
      type: string
      description: Código del usuario con el que se autentica en los sistemas.
      minLength: 5
      maxLength: 20
      example: jp2590
    Default_User_Password:
      type: string
      description: Contraseña del usuario.
      minLength: 8
      maxLength: 32
      format: password
      example: Temp12309$
    Default_Customer_Id:
      type: string
      description: Identificador del cliente en los sistemas de los bancos.
      minLength: 1
      maxLength: 15
      example: 524865485688
    Default_Session_Id:
      type: string
      description: Token de sesión generado en formato base64.
      format: uuid
      minLength: 1
      maxLength: 50
      example: VBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHEl
  securitySchemes:
    basic:
      description: En el header 'Authorization' se envia 'Basic Key:Secret' donde 'Key:Secret' en Base64. Por ejemplo, para autorizarse como 'demo / p@55w0rd' se envía 'Basic ZGVtbzpwQDU1dzByZA==' en el header indicado.
      type: http
      scheme: basic
security:
  - basic: []





